import re

with open('/Users/roshan/.gemini/antigravity/scratch/projectmatch/app/layout.tsx', 'r') as f:
    content = f.read()

# Add description if not present
if 'description: ' not in content:
    content = content.replace(
        'export const metadata: Metadata = {\n  title: "Create Next App",\n  description: "Generated by create next app",\n};',
        'export const metadata: Metadata = {\n  title: "ProjectMatch",\n  description: "AI-Powered Team Formation Platform",\n  keywords: ["team", "formation", "ai", "matchmaking", "hackathon"],\n};'
    )
elif 'Create Next App' in content:
    content = content.replace('Create Next App', 'ProjectMatch')
    content = content.replace('Generated by create next app', 'AI-Powered Team Formation Platform')

with open('/Users/roshan/.gemini/antigravity/scratch/projectmatch/app/layout.tsx', 'w') as f:
    f.write(content)
