"use client";

import { useState } from "react";
import { BlurFade } from "@/components/motion-primitives/blur-fade";
import { TextEffect } from "@/components/motion-primitives/text-effect";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Cpu, Sparkles, UserPlus, CheckCircle2, ArrowRight, Loader2, Calendar } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { MOCK_USERS } from "@/lib/mockData";

const PRESET_SKILLS = [
  // Hardware & Edge
  "Embedded Systems", "C", "C++", "Python", "Edge AI", "PCB Design", "AutoCAD", "ROS", "Arduino", "Raspberry Pi", "VHDL", "Verilog", "IoT", "Microcontrollers",
  // Software & Web
  "React", "Node.js", "TypeScript", "Tailwind CSS", "Next.js", "GraphQL", "PostgreSQL", "MongoDB", "Docker", "Kubernetes", "AWS",
  // AI & Data
  "PyTorch", "TensorFlow", "Computer Vision", "OpenCV", "NLP", "Pandas", "Scikit-Learn",
  // Web3 & Design
  "Solidity", "Smart Contracts", "Web3.js", "Figma", "UI/UX", "User Research"
];

export default function AIMatcherPage() {
  const [step, setStep] = useState<1 | 2 | 3 | 4>(1);
  const [idea, setIdea] = useState("");
  const [loading, setLoading] = useState(false);
  
  // Generated by AI in Step 2
  const [requiredSkills, setRequiredSkills] = useState<string[]>([]);
  const [timeline, setTimeline] = useState("");
  
  // User input in Step 3
  const [availableSkills, setAvailableSkills] = useState<string[]>([]);
  
  // Final calculation in Step 4
  const [matches, setMatches] = useState<any[]>([]);

  const toggleAvailableSkill = (skill: string) => {
    setAvailableSkills(prev => 
      prev.includes(skill) ? prev.filter(s => s !== skill) : [...prev, skill]
    );
  };

  const handleAnalyzeIdea = () => {
    if (!idea.trim()) return;
    setLoading(true);
    // Simulate AI parsing idea to find required skills
    setTimeout(() => {
      // Mock AI extraction logic
      const extracted = PRESET_SKILLS.sort(() => 0.5 - Math.random()).slice(0, 5);
      setRequiredSkills(extracted);
      setTimeline("8-10 Weeks (MVP)");
      setLoading(false);
      setStep(2);
    }, 1500);
  };

  const handleMatchCandidates = () => {
    setLoading(true);
    setTimeout(() => {
      // Calculate Missing Skills
      const missing = requiredSkills.filter(s => !availableSkills.includes(s));
      
      // Jaccard similarity matching against missing skills
      const scoredUsers = MOCK_USERS.map(user => {
        const candidateSkills = user.skills.map(s => s.toLowerCase());
        const missingLower = missing.map(s => s.toLowerCase());
        
        const intersection = missingLower.filter(m => 
          candidateSkills.some(c => c.includes(m) || m.includes(c))
        );

        const rawScore = missingLower.length > 0 
          ? (intersection.length / missingLower.length) * 100
          : 0;
        
        const matchPercentage = Math.max(rawScore > 0 ? rawScore : 5, Math.round(rawScore));

        return {
          ...user,
          matchPercentage: Math.min(100, Math.round(matchPercentage))
        };
      });

      const topMatches = scoredUsers
        .sort((a, b) => b.matchPercentage - a.matchPercentage)
        .slice(0, 3);

      setMatches(topMatches);
      setLoading(false);
      setStep(4);
    }, 2000);
  };

  return (
    <div className="max-w-5xl mx-auto px-6 py-10">
      <div className="text-center mb-12">
        <div className="w-16 h-16 rounded-2xl bg-nexa-blue/10 flex items-center justify-center mx-auto mb-6 border border-nexa-blue/20 shadow-lg shadow-nexa-blue/10">
          <Cpu className="text-nexa-blue w-8 h-8" />
        </div>
        <TextEffect text="AI Teammate Generator" className="text-3xl font-bold text-white justify-center" />
        <BlurFade delay={0.2}>
          <p className="text-nexa-lavender mt-3 max-w-lg mx-auto">
            Our autonomous analyzer breaks down your project requirements and hunts for the perfect missing link in your team.
          </p>
        </BlurFade>
      </div>

      <div className="max-w-3xl mx-auto">
        <AnimatePresence mode="wait">
          {/* STEP 1: IDEA */}
          {step === 1 && (
            <motion.div 
              key="step1"
              initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }}
              className="bg-nexa-card-dark border border-white/5 p-8 rounded-[32px] shadow-xl shadow-black/50"
            >
              <h3 className="text-xl font-bold text-white mb-2">Step 1: The Vision</h3>
              <p className="text-nexa-lavender mb-6">Describe what you want to build in plain English.</p>
              
              <Textarea 
                value={idea}
                onChange={(e) => setIdea(e.target.value)}
                placeholder="e.g. A voice-controlled edge AI robot that sorts recyclable materials using OpenCV..."
                className="bg-black/40 border-white/10 rounded-xl h-40 resize-none focus:border-nexa-accent focus:ring-nexa-accent text-white mb-6 text-lg p-4"
              />
              
              <div className="flex justify-end">
                <Button 
                  onClick={handleAnalyzeIdea}
                  disabled={loading || !idea.trim()}
                  className="nexa-grad-bg text-white rounded-xl h-12 px-8 border-0 shadow-lg shadow-nexa-accent/20 text-md"
                >
                  {loading ? <><Loader2 className="mr-2 animate-spin" /> Processing...</> : <>Analyze Architecture <Sparkles className="ml-2 w-4 h-4" /></>}
                </Button>
              </div>
            </motion.div>
          )}

          {/* STEP 2 & 3: REQUIRED SKILLS & AVAILABLE SKILLS */}
          {(step === 2 || step === 3) && (
            <motion.div 
              key="step23"
              initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }}
              className="space-y-6"
            >
              <div className="bg-nexa-card-dark border border-nexa-blue/30 p-8 rounded-[32px] shadow-[0_0_30px_rgba(28,78,255,0.1)] relative overflow-hidden">
                <div className="absolute top-0 right-0 p-6 opacity-20">
                  <Cpu className="w-24 h-24 text-nexa-blue" />
                </div>
                
                <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                  <CheckCircle2 className="text-nexa-blue" /> AI Analysis Complete
                </h3>
                
                <div className="grid md:grid-cols-2 gap-8 relative z-10">
                  <div>
                    <h4 className="text-sm font-semibold text-nexa-lavender-3 uppercase tracking-wider mb-3">Required Technical Stack</h4>
                    <div className="flex flex-wrap gap-2">
                      {requiredSkills.map(skill => (
                        <span key={skill} className="px-3 py-1.5 bg-nexa-blue/10 text-nexa-blue border border-nexa-blue/20 rounded-xl text-sm font-medium">
                          {skill}
                        </span>
                      ))}
                    </div>
                  </div>
                  <div>
                    <h4 className="text-sm font-semibold text-nexa-lavender-3 uppercase tracking-wider mb-3">Estimated Timeline</h4>
                    <div className="flex items-center gap-2 text-white bg-white/5 border border-white/10 w-fit px-4 py-2 rounded-xl">
                      <Calendar className="text-nexa-accent w-5 h-5" />
                      <span className="font-medium">{timeline}</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="bg-nexa-card-dark border border-white/5 p-8 rounded-[32px] shadow-xl shadow-black/50">
                <h3 className="text-xl font-bold text-white mb-2">Step 2: Skill Balancing</h3>
                <p className="text-nexa-lavender mb-6">Select the skills you already bring to the table. The AI will hunt for the missing pieces.</p>
                
                <div className="flex flex-wrap gap-2 mb-8">
                  {PRESET_SKILLS.map(skill => {
                    const isSelected = availableSkills.includes(skill);
                    const isRequired = requiredSkills.includes(skill);
                    
                    return (
                      <button
                        key={skill}
                        onClick={() => toggleAvailableSkill(skill)}
                        className={`px-4 py-2 rounded-xl text-sm font-medium transition-all border ${
                          isSelected 
                            ? 'bg-nexa-accent text-white border-nexa-accent shadow-lg shadow-nexa-accent/20' 
                            : isRequired
                              ? 'bg-nexa-accent/10 text-nexa-accent border-nexa-accent/30 hover:bg-nexa-accent/20'
                              : 'bg-white/5 text-nexa-lavender border-white/10 hover:bg-white/10 hover:text-white'
                        }`}
                      >
                        {skill}
                      </button>
                    )
                  })}
                </div>

                <div className="flex justify-end">
                  <Button 
                    onClick={handleMatchCandidates}
                    disabled={loading}
                    className="nexa-grad-bg text-white rounded-xl h-12 px-8 border-0 shadow-lg shadow-nexa-accent/20 text-md"
                  >
                    {loading ? <><Loader2 className="mr-2 animate-spin" /> Cross-referencing DB...</> : <>Find Missing Teammates <ArrowRight className="ml-2 w-4 h-4" /></>}
                  </Button>
                </div>
              </div>
            </motion.div>
          )}

          {/* STEP 4: RESULTS */}
          {step === 4 && (
            <motion.div 
              key="step4"
              initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
              className="space-y-6"
            >
              <div className="bg-nexa-card-dark border border-nexa-accent/30 p-6 rounded-[24px] flex items-center justify-between">
                <div>
                  <h4 className="text-sm font-semibold text-nexa-lavender-3 uppercase tracking-wider mb-2">Calculated Missing Skills</h4>
                  <div className="flex flex-wrap gap-2">
                    {requiredSkills.filter(s => !availableSkills.includes(s)).map(skill => (
                      <span key={skill} className="px-3 py-1 bg-nexa-orange/10 text-nexa-orange border border-nexa-orange/20 rounded-lg text-sm font-medium">
                        {skill}
                      </span>
                    ))}
                    {requiredSkills.filter(s => !availableSkills.includes(s)).length === 0 && (
                      <span className="text-emerald-400 font-medium text-sm">You have all required skills!</span>
                    )}
                  </div>
                </div>
                <Button variant="outline" onClick={() => setStep(1)} className="bg-white/5 border-white/10 text-white rounded-xl">
                  Start Over
                </Button>
              </div>

              <div className="space-y-4">
                <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                  Top Matched Candidates
                </h3>
                {matches.map((candidate, idx) => (
                  <motion.div 
                    initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: idx * 0.1 }}
                    key={candidate.id} 
                    className="bg-nexa-card-dark border border-white/5 rounded-2xl p-5 shadow-xl shadow-black/50 flex flex-col sm:flex-row gap-5 items-start sm:items-center relative overflow-hidden group hover:border-white/10 transition-colors"
                  >
                    <div className="absolute top-0 right-0 w-32 h-32 bg-nexa-blue/10 rounded-full blur-[40px] -z-10 translate-x-1/2 -translate-y-1/2 group-hover:bg-nexa-blue/20 transition-colors" />
                    
                    <Avatar className="w-16 h-16 border-2 border-nexa-blue/30 shrink-0">
                      <AvatarImage src={candidate.avatar} />
                      <AvatarFallback className="bg-nexa-blue text-white font-bold">{candidate.name[0]}</AvatarFallback>
                    </Avatar>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between mb-1">
                        <h4 className="text-lg font-bold text-white truncate">{candidate.name}</h4>
                        <div className="flex items-center gap-1">
                          <span className="text-xs font-semibold text-nexa-lavender-3 uppercase">Match</span>
                          <span className={`text-sm font-bold px-2 py-0.5 rounded-md ${
                            candidate.matchPercentage >= 80 ? 'bg-emerald-500/10 text-emerald-400' :
                            candidate.matchPercentage >= 40 ? 'bg-nexa-blue/10 text-nexa-blue' :
                            'bg-white/5 text-white/50'
                          }`}>
                            {candidate.matchPercentage}%
                          </span>
                        </div>
                      </div>
                      <p className="text-sm text-nexa-lavender mb-3">{candidate.role}</p>
                      
                      <div className="flex flex-wrap gap-1.5">
                        {candidate.skills.slice(0, 5).map((skill: string) => (
                          <span key={skill} className="text-xs px-2 py-1 bg-white/5 border border-white/5 rounded-md text-white/70">
                            {skill}
                          </span>
                        ))}
                      </div>
                    </div>

                    <div className="w-full sm:w-auto mt-4 sm:mt-0 shrink-0">
                      <Button className="w-full sm:w-auto bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-xl h-10">
                        <UserPlus size={16} className="mr-2" /> Invite to Team
                      </Button>
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
